code fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,30 +18,30 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
-      - name: Deploy to DigitalOcean
-        run: |
-          # Connect to DigitalOcean Droplet
-          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
-            echo "Connected to server"
+      # - name: Deploy to DigitalOcean
+      #   run: |
+      #     # Connect to DigitalOcean Droplet
+      #     ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
+      #       echo "Connected to server"
 
-            # Navigate to the project directory
-            cd ~/crypto-verse
+      #       # Navigate to the project directory
+      #       cd ~/crypto-verse
 
-            # Reset any uncommitted changes
-            git reset --hard
+      #       # Reset any uncommitted changes
+      #       git reset --hard
 
-            # Ensure we are on the main branch and pull the latest changes
-            git checkout main
-            git pull origin main || { echo 'Git pull failed, aborting deployment.'; exit 1; }
+      #       # Ensure we are on the main branch and pull the latest changes
+      #       git checkout main
+      #       git pull origin main || { echo 'Git pull failed, aborting deployment.'; exit 1; }
 
-            # Install dependencies
-            npm install || { echo 'npm install failed, aborting deployment.'; exit 1; }
+      #       # Install dependencies
+      #       npm install || { echo 'npm install failed, aborting deployment.'; exit 1; }
 
-            # Build the project
-            npm run build || { echo 'Build failed, aborting deployment.'; exit 1; }
+      #       # Build the project
+      #       npm run build || { echo 'Build failed, aborting deployment.'; exit 1; }
 
-            # Restart PM2 processes
-            pm2 restart 0 || { echo 'PM2 restart failed, aborting deployment.'; exit 1; }
+      #       # Restart PM2 processes
+      #       pm2 restart 0 || { echo 'PM2 restart failed, aborting deployment.'; exit 1; }
 
-            echo "Deployment successful!"
-          EOF
+      #       echo "Deployment successful!"
+      #     EOF
